tenable:
  # Tenable.io or API Access Key
  access_key:

  # Tenable.io or API Secret Key
  secret_key:

jira:
  # The API Token to use to authenticate to the Jira application
  api_token:

  # The User that will be authenticaing to the Jira application
  api_username:

  # The address pointing to the Jira application.
  address: your-domain.atlassian.net